-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.applications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  full_name text NOT NULL,
  email text NOT NULL CHECK (email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'::text),
  role text NOT NULL CHECK (role = ANY (ARRAY['vendor'::text, 'deliverer'::text, 'admin'::text])),
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'declined'::text])),
  organization text,
  notes text,
  document_urls jsonb DEFAULT '[]'::jsonb,
  business_name text,
  business_address text,
  menu_summary text,
  vehicle_type text,
  availability text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  reviewed_at timestamp with time zone,
  reviewed_by uuid,
  CONSTRAINT applications_pkey PRIMARY KEY (id),
  CONSTRAINT applications_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT applications_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  vendor_id uuid NOT NULL,
  name text NOT NULL,
  display_order integer DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT categories_pkey PRIMARY KEY (id),
  CONSTRAINT categories_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendors(id)
);
CREATE TABLE public.menu_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  vendor_id uuid NOT NULL,
  category_id uuid,
  name text NOT NULL,
  description text,
  price numeric NOT NULL CHECK (price >= 0::numeric),
  image_url text,
  is_available boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  is_best_seller boolean DEFAULT false,
  is_recommended boolean DEFAULT false,
  CONSTRAINT menu_items_pkey PRIMARY KEY (id),
  CONSTRAINT menu_items_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendors(id),
  CONSTRAINT menu_items_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id)
);
CREATE TABLE public.messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL,
  sender_id uuid NOT NULL,
  message text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  read boolean NOT NULL DEFAULT false,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT messages_pkey PRIMARY KEY (id),
  CONSTRAINT messages_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  customer_id uuid NOT NULL,
  vendor_id uuid NOT NULL,
  deliverer_id uuid,
  items jsonb NOT NULL,
  total_price numeric NOT NULL CHECK (total_price >= 0::numeric),
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'preparing'::text, 'ready'::text, 'accepted'::text, 'on_the_way'::text, 'delivered'::text, 'completed'::text, 'cancelled'::text])),
  delivery_address text,
  delivery_notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  prepared_at timestamp with time zone,
  accepted_at timestamp with time zone,
  delivered_at timestamp with time zone,
  completed_at timestamp with time zone,
  customer_name text,
  customer_phone text,
  delivery_fee numeric DEFAULT 0,
  delivery_latitude numeric,
  delivery_longitude numeric,
  pickup_latitude numeric,
  pickup_longitude numeric,
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  CONSTRAINT orders_pkey PRIMARY KEY (id),
  CONSTRAINT orders_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.profiles(id),
  CONSTRAINT orders_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendors(id),
  CONSTRAINT orders_deliverer_id_fkey FOREIGN KEY (deliverer_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.organizations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  slug text NOT NULL UNIQUE,
  email_domains ARRAY NOT NULL,
  auth_methods ARRAY DEFAULT ARRAY['oauth_google'::text, 'magic_link'::text],
  oauth_google_enabled boolean DEFAULT true,
  oauth_microsoft_enabled boolean DEFAULT false,
  saml_sso_enabled boolean DEFAULT false,
  saml_metadata_url text,
  logo_url text,
  header_image_url text,
  primary_color text DEFAULT '#4F46E5'::text,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text, 'suspended'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT organizations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  role text NOT NULL CHECK (role = ANY (ARRAY['customer'::text, 'vendor'::text, 'deliverer'::text, 'admin'::text, 'superadmin'::text])),
  full_name text,
  email text NOT NULL CHECK (email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'::text),
  organization text DEFAULT 'global'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'declined'::text])),
  phone text,
  delivery_address text,
  delivery_notes text,
  latitude numeric,
  longitude numeric,
  profile_picture_url text,
  header_image_url text,
  organization_id uuid,
  auth_provider text,
  email_verified boolean DEFAULT false,
  last_login_at timestamp with time zone,
  metadata jsonb DEFAULT '{}'::jsonb,
  invite_token text UNIQUE,
  invite_token_expires timestamp with time zone,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
  CONSTRAINT profiles_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.ratings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL,
  customer_id uuid NOT NULL,
  rated_entity_id uuid NOT NULL,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  comment text,
  type text NOT NULL CHECK (type = ANY (ARRAY['vendor'::text, 'deliverer'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ratings_pkey PRIMARY KEY (id),
  CONSTRAINT ratings_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT ratings_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.vendor_reports_archive (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  vendor_id uuid NOT NULL,
  month integer NOT NULL CHECK (month >= 1 AND month <= 12),
  year integer NOT NULL,
  total_revenue numeric DEFAULT 0,
  total_orders integer DEFAULT 0,
  average_order_value numeric DEFAULT 0,
  delivery_fees numeric DEFAULT 0,
  net_revenue numeric DEFAULT 0,
  top_selling_items jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  least_selling_items jsonb DEFAULT '[]'::jsonb,
  CONSTRAINT vendor_reports_archive_pkey PRIMARY KEY (id),
  CONSTRAINT vendor_reports_archive_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.vendors (
  id uuid NOT NULL,
  business_name text NOT NULL,
  business_address text,
  menu_summary text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  delivery_fee numeric DEFAULT 0 CHECK (delivery_fee >= 0::numeric),
  minimum_order numeric DEFAULT 0 CHECK (minimum_order >= 0::numeric),
  header_image_url text,
  latitude numeric,
  longitude numeric,
  CONSTRAINT vendors_pkey PRIMARY KEY (id),
  CONSTRAINT vendors_id_fkey FOREIGN KEY (id) REFERENCES public.profiles(id)
);